// <auto-generated />
using Api.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Migrations
{
    [DbContext(typeof(SeatContext))]
    partial class SeatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api.Models.Seat", b =>
                {
                    b.Property<string>("SeatId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Reservable");

                    b.HasKey("SeatId")
                        .HasName("PrimaryKey_SeatId");

                    b.ToTable("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
